// Mocks generated by Mockito 5.0.15 from annotations
// in audifie_version_1/test/features/settings/data/data_source/remote_data_source_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:audifie_version_1/core/services/email_sender_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [EmailSenderService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmailSenderService extends _i1.Mock
    implements _i2.EmailSenderService {
  MockEmailSenderService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> sendEmail(
          {String? body,
          String? subject,
          List<String>? recipients,
          List<String>? attachmentPaths = const []}) =>
      (super.noSuchMethod(
          Invocation.method(#sendEmail, [], {
            #body: body,
            #subject: subject,
            #recipients: recipients,
            #attachmentPaths: attachmentPaths
          }),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  String toString() => super.toString();
}
